highlighter: true

description: The Hydramata Project development blog
url: http://hydramata.github.io
name: Hydramata Project

permalink: /:categories/:title/

exclude:
  - .gitingore
  - README.md
  - Gemfile
  - Gemfile.lock
